# Uncomment the next line to define a global platform for your project
# platform :iOS, '9.0'

target 'Face' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Face

  target 'FaceTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FaceUITests' do
    # Pods for testing
  end

pod 'GoogleMLKit/FaceDetection', '2.6.0'



end
